create_clock -name core_clk -period 1.250 [get_ports clk]
set_clock_uncertainty 0.100 [get_clocks core_clk]
set_input_delay 0.150 -clock core_clk [remove_from_collection [all_inputs] [get_ports clk]]
set_output_delay 0.150 -clock core_clk [all_outputs]
set_false_path -from [get_ports rst_n]
set_load 0.020 [all_outputs]
