#!/usr/bin/env bash
# Create (or re-sync) the Postgres roles and databases for the AIMEM platform.
#
# Idempotent. Touches only these objects, on the server at $PGHOST:$PGPORT:
#   roles      aimem_platform_owner (runs migrations), aimem_platform_app (runtime)
#   databases  aimem_platform (dev), aimem_platform_test (disposable, used by pytest)
# Undo:
#   DROP DATABASE aimem_platform; DROP DATABASE aimem_platform_test;
#   DROP ROLE aimem_platform_app; DROP ROLE aimem_platform_owner;
#
# Writes platform/.env (mode 600) with generated passwords the first time, and
# re-applies those passwords to the roles on later runs.
set -euo pipefail
cd "$(dirname "$0")/.."

PGHOST="${PGHOST:-localhost}"
PGPORT="${PGPORT:-5432}"
ADMIN_DB="${AIMEM_SETUP_ADMIN_DB:-postgres}"
OWNER_ROLE=aimem_platform_owner
APP_ROLE=aimem_platform_app
DEV_DB=aimem_platform
TEST_DB=aimem_platform_test
ENV_FILE=.env

read_env() {
  if [ -f "$ENV_FILE" ]; then
    grep -E "^$1=" "$ENV_FILE" | head -n 1 | cut -d= -f2- || true
  fi
}
new_secret() { python3 -c 'import secrets; print(secrets.token_urlsafe(24))'; }

OWNER_PASSWORD="$(read_env AIMEM_SETUP_OWNER_PASSWORD)"
APP_PASSWORD="$(read_env AIMEM_SETUP_APP_PASSWORD)"
[ -n "$OWNER_PASSWORD" ] || OWNER_PASSWORD="$(new_secret)"
[ -n "$APP_PASSWORD" ] || APP_PASSWORD="$(new_secret)"
for secret in "$OWNER_PASSWORD" "$APP_PASSWORD"; do
  [[ "$secret" =~ ^[A-Za-z0-9_-]+$ ]] || { echo "refusing: generated passwords must be URL-safe" >&2; exit 1; }
done

psql -h "$PGHOST" -p "$PGPORT" -d "$ADMIN_DB" -v ON_ERROR_STOP=1 -q <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$OWNER_ROLE') THEN
    CREATE ROLE $OWNER_ROLE LOGIN PASSWORD '$OWNER_PASSWORD';
  ELSE
    ALTER ROLE $OWNER_ROLE LOGIN PASSWORD '$OWNER_PASSWORD';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$APP_ROLE') THEN
    CREATE ROLE $APP_ROLE LOGIN PASSWORD '$APP_PASSWORD';
  ELSE
    ALTER ROLE $APP_ROLE LOGIN PASSWORD '$APP_PASSWORD';
  END IF;
END
\$\$;
SELECT format('CREATE DATABASE %I OWNER %I', '$DEV_DB', '$OWNER_ROLE')
  WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$DEV_DB') \gexec
SELECT format('CREATE DATABASE %I OWNER %I', '$TEST_DB', '$OWNER_ROLE')
  WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$TEST_DB') \gexec
REVOKE CONNECT, TEMPORARY ON DATABASE $DEV_DB FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE $TEST_DB FROM PUBLIC;
GRANT CONNECT ON DATABASE $DEV_DB TO $OWNER_ROLE, $APP_ROLE;
GRANT CONNECT ON DATABASE $TEST_DB TO $OWNER_ROLE, $APP_ROLE;
SQL

url() { echo "postgresql+psycopg://$1:$2@$PGHOST:$PGPORT/$3"; }

if [ ! -f "$ENV_FILE" ]; then
  umask 077
  cat > "$ENV_FILE" <<ENV
# Generated by platform/scripts/setup-local-db.sh. Local development only; never commit.
AIMEM_DATABASE_URL=$(url "$APP_ROLE" "$APP_PASSWORD" "$DEV_DB")
AIMEM_OWNER_DATABASE_URL=$(url "$OWNER_ROLE" "$OWNER_PASSWORD" "$DEV_DB")
AIMEM_TEST_DATABASE_URL=$(url "$APP_ROLE" "$APP_PASSWORD" "$TEST_DB")
AIMEM_TEST_OWNER_DATABASE_URL=$(url "$OWNER_ROLE" "$OWNER_PASSWORD" "$TEST_DB")
AIMEM_SETUP_OWNER_PASSWORD=$OWNER_PASSWORD
AIMEM_SETUP_APP_PASSWORD=$APP_PASSWORD
ENV
  echo "Wrote platform/$ENV_FILE"
else
  echo "Kept existing platform/$ENV_FILE"
fi
echo "Roles $OWNER_ROLE, $APP_ROLE and databases $DEV_DB, $TEST_DB are ready on $PGHOST:$PGPORT."
